const fakeApiJSON = [
  {
    id: 1,
    name: "Sandra",
    surname: "Gómez",
    age: 21,
    isNear: false,
    nearKm: 0,
    city: "Surco",
    country: "Peru",
    interests: ["Viajar", "Leer", "Amistad", "Pasarlo bien", "Salir de fiesta"],
    selfConsider: false,
    selfConsiderTag: "",
    match: false,
    urlImg:
      "https://res.cloudinary.com/df5faxxou/image/upload/fl_preserve_transparency/v1745445024/modelo2_mui7xh.jpg?_s=public-apps",
    lists: ["Friendship"],
  },
  {
    id: 2,
    name: "Beatriz",
    surname: "",
    age: 22,
    isNear: true,
    nearKm: 22,
    city: "Lima",
    country: "",
    interests: ["Viajar", "Leer", "Salir de fiesta"],
    selfConsider: true,
    selfConsiderTag: "Femme",
    match: true,
    urlImg:
      "https://res.cloudinary.com/df5faxxou/image/upload/fl_preserve_transparency/v1745445023/modelo4_woi1kw.jpg?_s=public-apps",
    lists: ["Dates"],
  },
  {
    id: 3,
    name: "Carmen",
    surname: "",
    age: 22,
    isNear: false,
    nearKm: 0,
    city: "Miraflores",
    country: "Peru",
    interests: ["Viajar", "Leer", "Salir de fiesta"],
    selfConsider: true,
    selfConsiderTag: "Femme",
    match: false,
    urlImg:
      "https://res.cloudinary.com/df5faxxou/image/upload/fl_preserve_transparency/v1745445023/modelo1_fyc5zk.jpg?_s=public-apps",
    lists: ["Relationship", "Friendship"],
  },
  {
    id: 4,
    name: "Alondra",
    surname: "",
    age: 27,
    isNear: false,
    nearKm: 0,
    city: "San Isidro",
    country: "Peru",
    interests: ["Viajar", "Leer", "Amistad"],
    selfConsider: false,
    selfConsiderTag: "",
    match: true,
    urlImg:
      "https://res.cloudinary.com/df5faxxou/image/upload/fl_preserve_transparency/v1745445023/modelo3_njirb4.jpg?_s=public-apps",
    lists: ["Friendship", "Dates"],
  },
  {
    id: 5,
    name: "Ana",
    surname: "",
    age: 22,
    isNear: true,
    nearKm: 30,
    city: "Lima",
    country: "",
    interests: ["Viajar", "Leer", "Amistad"],
    selfConsider: false,
    selfConsiderTag: "",
    match: false,
    urlImg:
      "https://res.cloudinary.com/df5faxxou/image/upload/fl_preserve_transparency/v1745445023/modelo5_eoa8ws.jpg?_s=public-apps",
    lists: ["Dates", "Relationship"],
  },
  {
    id: 6,
    name: "María",
    surname: "",
    age: 19,
    isNear: false,
    nearKm: 0,
    city: "Miraflores",
    country: "Peru",
    interests: ["Amistad"],
    selfConsider: false,
    selfConsiderTag: "",
    match: true,
    urlImg:
      "https://res.cloudinary.com/df5faxxou/image/upload/fl_preserve_transparency/v1745445023/modelo6_g97y3l.jpg?_s=public-apps",
    lists: ["Relationship", "Dates"],
  },
];

export default fakeApiJSON;
